---
name: Lint and test workflow
on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.base_ref }}

      - name: Setup Python environment
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          environments: >-
            dev-only
          activate-environment: dev-only

      - name: isort
        run: isort spimquant/*.py -c --profile black

      - name: Black
        run: black spimquant --check

      - name: snakefmt
        run: snakefmt spimquant --check

  test:
    runs-on: ubuntu-latest
    needs: ["quality"]
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Setup Pixi environment
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          activate-environment: true
      
      - name: Dry-run Test
        run: |
          ./spimquant/run.py $GITHUB_WORKSPACE/tests/bids_ds test_out participant -np

      - name: Dry-run Test with MRI reg
        run: |
          ./spimquant/run.py $GITHUB_WORKSPACE/tests/bids_ds_withmri test_out participant -np --register-to-mri

      - name: Dry-run Test with MRI reg, no segmentation
        run: |
          ./spimquant/run.py $GITHUB_WORKSPACE/tests/bids_ds_withmri test_out participant -np --register-to-mri --no-segmentation
